apiVersion: v1
kind: Secret
metadata:
  name: filevault-secrets
type: Opaque
stringData:
  azure-storage-account-name: "filevaultstorage2025"
  azure-storage-account-key: "YOUR_AZURE_STORAGE_KEY_HERE"
  azure-container-name: "YOUR_CONTAINER_NAME_HERE"
